apiVersion: v1
kind: Service
metadata:
  name: instastories-web-service
  namespace: instastories-namespace
spec:
  type: NodePort
  selector:
    app: instastories
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      #targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: instastories-web-deployment
  namespace: instastories-namespace
  labels:
    app: instastories
spec:
  replicas: 1
  selector:
    matchLabels:
      app: instastories
      tier: frontend
  template:
    metadata:
      labels:
        app: instastories
        tier: frontend
    spec:
      containers:
      - name: instastories
        image: hpfpv/instastories-web:latest
        resources:
          limits:
            memory: 256Mi
            cpu: "0.5"
          requests:
            memory: 128Mi
            cpu: "0.2"
        env:
        - name: API_ENDPOINT
          valueFrom: 
            configMapKeyRef:
              name: instastories-api-config
              key: api-endpoint
        ports:
        - containerPort: 80
        
        
        
