apiVersion: v1
kind: Service
metadata:
  name: instastories-mongo-express-service
  namespace: instastories-namespace
spec:
  type: NodePort
  selector:
    app: instastories
    tier: mongo-express
  ports:
    - protocol: TCP
      port: 8081
      nodePort: 30110
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: instastories-mongo-express-deployment
  namespace: instastories-namespace
  labels:
    app: instastories
spec:
  replicas: 1
  selector:
    matchLabels:
      app: instastories
      tier: mongo-express
  template:
    metadata:
      labels:
        app: instastories
        tier: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        resources:
          limits:
            memory: 128Mi
            cpu: "0.2"
          requests:
            memory: 64Mi
            cpu: "0.1"
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom: 
            secretKeyRef:
              name: instastories-mongo-secret
              key: mongo-user
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom: 
            secretKeyRef:
              name: instastories-mongo-secret
              key: mongo-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom: 
            configMapKeyRef:
              name: instastories-mongo-config
              key: mongo-url
        ports:
        - containerPort: 8081

